- name: install and run nginx
  hosts: httpd
  become: yes # -b
  tasks:
  - name: install httpd
    ansible.builtin.package:
      name: httpd
      state: present
  - name: start the nginx
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes